import { Activity, AlertCircle, AlignLeft, Award, BarChart, Bell, Brush, Calendar, Camera, Check, ChevronDown, ChevronLeft, ChevronRight, Circle, Clock, Code, CreditCard, DollarSign, Download, File, FileText, Filter, Flag, Folder, FormInput, Grid3X3, Hash, Home, ImageIcon, Info, Layout, Link, List, Lock, Mail, MapPin, Maximize, Menu, MessageSquare, Minimize, Music, Navigation, Phone, Play, Quote, RotateCcw, Search, Share, ShoppingCart, Smartphone, Square, Star, Tag, Target, ToggleLeft, TrendingUp, Type, Upload, User, Users, Video, X } from "lucide-react"

export const componentCategories = [
  {
    name: "Basic Elements",
    components: [
      { name: "Heading", icon: Type, description: "H1, H2, H3 headings", type: "heading" },
      { name: "Paragraph", icon: AlignLeft, description: "Text content", type: "paragraph" },
      { name: "Image", icon: ImageIcon, description: "Images and media", type: "image" },
      { name: "Button", icon: Square, description: "Interactive buttons", type: "button" },
      { name: "Card", icon: Square, description: "Content cards", type: "card" },
      { name: "Quote", icon: Quote, description: "Blockquotes", type: "quote" },
      { name: "Separator", icon: Layout, description: "Dividers", type: "separator" },
      { name: "List", icon: List, description: "Bulleted lists", type: "list" },
    ],
  },
  {
    name: "Layout",
    components: [
      { name: "Section", icon: Layout, description: "Content sections", type: "section" },
      { name: "Grid", icon: Grid3X3, description: "Grid layouts", type: "grid" },
      { name: "Navigation", icon: Navigation, description: "Nav menus", type: "navigation" },
      { name: "Footer", icon: FileText, description: "Page footers", type: "footer" },
      { name: "Header", icon: Layout, description: "Page headers", type: "header" },
      { name: "Sidebar", icon: Layout, description: "Side panels", type: "sidebar" },
    ],
  },
  {
    name: "Forms & Inputs",
    components: [
      { name: "Form", icon: FormInput, description: "Contact forms", type: "form" },
      { name: "Input", icon: FormInput, description: "Text inputs", type: "input" },
      { name: "Textarea", icon: AlignLeft, description: "Multi-line text", type: "textarea" },
      { name: "Select", icon: ChevronDown, description: "Dropdown menus", type: "select" },
      { name: "Checkbox", icon: Check, description: "Checkboxes", type: "checkbox" },
      { name: "Radio", icon: Circle, description: "Radio buttons", type: "radio" },
      { name: "Switch", icon: ToggleLeft, description: "Toggle switches", type: "switch" },
    ],
  },
  {
    name: "Media & Icons",
    components: [
      { name: "Video", icon: Video, description: "Video players", type: "video" },
      { name: "Audio", icon: Music, description: "Audio players", type: "audio" },
      { name: "Gallery", icon: Camera, description: "Image galleries", type: "gallery" },
      { name: "Icon", icon: Star, description: "Icons", type: "icon" },
      { name: "Badge", icon: Award, description: "Status badges", type: "badge" },
      { name: "Avatar", icon: User, description: "User avatars", type: "avatar" },
    ],
  },
  {
    name: "Interactive",
    components: [
      { name: "Modal", icon: Maximize, description: "Pop-up modals", type: "modal" },
      { name: "Tooltip", icon: Info, description: "Hover tooltips", type: "tooltip" },
      { name: "Dropdown", icon: ChevronDown, description: "Dropdown menus", type: "dropdown" },
      { name: "Tabs", icon: Layout, description: "Tabbed content", type: "tabs" },
      { name: "Accordion", icon: ChevronDown, description: "Collapsible content", type: "accordion" },
      { name: "Carousel", icon: ChevronLeft, description: "Image carousels", type: "carousel" },
    ],
  },
  {
    name: "Data Display",
    components: [
      { name: "Table", icon: Grid3X3, description: "Data tables", type: "table" },
      { name: "Chart", icon: BarChart, description: "Data charts", type: "chart" },
      { name: "Progress", icon: Activity, description: "Progress bars", type: "progress" },
      { name: "Timeline", icon: Clock, description: "Event timelines", type: "timeline" },
      { name: "Stats", icon: TrendingUp, description: "Statistics cards", type: "stats" },
      { name: "Counter", icon: Hash, description: "Number counters", type: "counter" },
    ],
  },
  {
    name: "E-commerce",
    components: [
      { name: "Product Card", icon: ShoppingCart, description: "Product displays", type: "product-card" },
      { name: "Price", icon: DollarSign, description: "Price displays", type: "price" },
      { name: "Rating", icon: Star, description: "Star ratings", type: "rating" },
      { name: "Cart", icon: ShoppingCart, description: "Shopping cart", type: "cart" },
      { name: "Checkout", icon: CreditCard, description: "Checkout forms", type: "checkout" },
    ],
  },
  {
    name: "Social & Contact",
    components: [
      { name: "Social Links", icon: Share, description: "Social media", type: "social-links" },
      { name: "Contact Info", icon: Phone, description: "Contact details", type: "contact-info" },
      { name: "Map", icon: MapPin, description: "Location maps", type: "map" },
      { name: "Newsletter", icon: Mail, description: "Email signup", type: "newsletter" },
      { name: "Team", icon: Users, description: "Team members", type: "team" },
      { name: "Testimonial", icon: Quote, description: "Customer reviews", type: "testimonial" },
    ],
  },
  {
    name: "Advanced UI",
    components: [
      { name: "Calendar", icon: Calendar, description: "Date picker", type: "calendar" },
      { name: "Search Bar", icon: Search, description: "Search input", type: "search-bar" },
      { name: "Filter", icon: Filter, description: "Filter controls", type: "filter" },
      { name: "Breadcrumb", icon: ChevronRight, description: "Navigation breadcrumbs", type: "breadcrumb" },
      { name: "Pagination", icon: ChevronLeft, description: "Page navigation", type: "pagination" },
      { name: "Alert", icon: AlertCircle, description: "Alert messages", type: "alert" },
      { name: "Toast", icon: Bell, description: "Toast notifications", type: "toast" },
      { name: "Drawer", icon: Minimize, description: "Side drawer", type: "drawer" },
    ],
  },
  {
    name: "Content & Text",
    components: [
      { name: "Code Block", icon: Code, description: "Code snippets", type: "code-block" },
      { name: "Markdown", icon: FileText, description: "Markdown content", type: "markdown" },
      { name: "Rich Text", icon: Type, description: "Rich text editor", type: "rich-text" },
      { name: "Typography", icon: Brush, description: "Text styles", type: "typography" },
      { name: "Link", icon: Link, description: "External links", type: "link" },
      { name: "Tag", icon: Tag, description: "Content tags", type: "tag" },
      { name: "Label", icon: Flag, description: "Text labels", type: "label" },
    ],
  },
  {
    name: "File & Media",
    components: [
      { name: "File Upload", icon: Upload, description: "File uploader", type: "file-upload" },
      { name: "File Download", icon: Download, description: "Download links", type: "file-download" },
      { name: "PDF Viewer", icon: File, description: "PDF display", type: "pdf-viewer" },
      { name: "Document", icon: FileText, description: "Document viewer", type: "document" },
      { name: "Folder", icon: Folder, description: "Folder structure", type: "folder" },
      { name: "Media Player", icon: Play, description: "Media controls", type: "media-player" },
    ],
  },
  {
    name: "Navigation & Menu",
    components: [
      { name: "Menu", icon: Menu, description: "Dropdown menu", type: "menu" },
      { name: "Tab Navigation", icon: Layout, description: "Tab menu", type: "tab-nav" },
      { name: "Side Menu", icon: Layout, description: "Side navigation", type: "side-menu" },
      { name: "Mobile Menu", icon: Smartphone, description: "Mobile nav", type: "mobile-menu" },
      { name: "Back Button", icon: ChevronLeft, description: "Go back", type: "back-button" },
      { name: "Home Button", icon: Home, description: "Home link", type: "home-button" },
    ],
  },
  {
    name: "Feedback & Status",
    components: [
      { name: "Loading", icon: RotateCcw, description: "Loading indicator", type: "loading" },
      { name: "Progress Ring", icon: Circle, description: "Circular progress", type: "progress-ring" },
      { name: "Status Badge", icon: Award, description: "Status indicator", type: "status-badge" },
      { name: "Notification", icon: Bell, description: "Notification bell", type: "notification" },
      { name: "Success Message", icon: Check, description: "Success alert", type: "success-message" },
      { name: "Error Message", icon: X, description: "Error alert", type: "error-message" },
      { name: "Warning Message", icon: AlertCircle, description: "Warning alert", type: "warning-message" },
    ],
  },
  {
    name: "Utility & Tools",
    components: [
      { name: "Spacer", icon: Square, description: "Empty space", type: "spacer" },
      { name: "Container", icon: Square, description: "Content wrapper", type: "container" },
      { name: "Wrapper", icon: Layout, description: "Element wrapper", type: "wrapper" },
      { name: "Flexbox", icon: Layout, description: "Flex container", type: "flexbox" },
      { name: "Center", icon: Circle, description: "Centered content", type: "center" },
      { name: "Stack", icon: Layout, description: "Vertical stack", type: "stack" },
    ],
  },
  {
    name: "Business & Marketing",
    components: [
      { name: "Pricing Table", icon: DollarSign, description: "Pricing plans", type: "pricing-table" },
      { name: "Feature List", icon: Check, description: "Feature highlights", type: "feature-list" },
      { name: "FAQ", icon: Info, description: "Frequently asked questions", type: "faq" },
      { name: "Blog Post", icon: FileText, description: "Blog article", type: "blog-post" },
      { name: "Case Study", icon: BarChart, description: "Success stories", type: "case-study" },
      { name: "Call to Action", icon: Target, description: "CTA sections", type: "cta" },
      { name: "Hero Section", icon: Star, description: "Landing hero", type: "hero" },
      { name: "About Section", icon: Users, description: "About us", type: "about" },
    ],
  },
  {
    name: "Forms & Validation",
    components: [
      { name: "Newsletter Signup", icon: Mail, description: "Email subscription", type: "newsletter-signup" },
      { name: "Login Form", icon: Lock, description: "User login", type: "login-form" },
      { name: "Registration Form", icon: User, description: "User signup", type: "registration-form" },
      { name: "Survey Form", icon: BarChart, description: "Feedback survey", type: "survey-form" },
      { name: "Order Form", icon: ShoppingCart, description: "Order placement", type: "order-form" },
      { name: "Booking Form", icon: Calendar, description: "Appointment booking", type: "booking-form" },
      { name: "Feedback Form", icon: MessageSquare, description: "User feedback", type: "feedback-form" },
    ],
  },
]