import type { Breakpoint, BuilderElement, BuilderPage } from "./builder-types"

export interface ExportOptions {
  includeResponsive: boolean
  minifyCode: boolean
  includeComments: boolean
  generateRouting?: boolean // For multi-page export
}

export function generateCSS(
  elements: BuilderElement[],
  options: ExportOptions = { includeResponsive: true, minifyCode: false, includeComments: true },
): string {
  let css = ""

  if (options.includeComments) {
    css += "/* Generated by Website Builder */\n"
    css += "/* Base styles */\n"
  }

  // Base CSS reset and utilities
  css += `
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  line-height: 1.6;
  color: #333;
}

img {
  max-width: 100%;
  height: auto;
}

button {
  cursor: pointer;
  border: none;
  outline: none;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 1rem;
}
`

  // Generate styles for each element
  elements.forEach((element, index) => {
    const className = `element-${element.id}`

    if (options.includeComments) {
      css += `\n/* ${element.type} - ${element.id} */\n`
    }

    css += `.${className} {\n`

    // Base styles
    Object.entries(element.styles || {}).forEach(([property, value]) => {
      css += `  ${camelToKebab(property)}: ${value};\n`
    })

    css += "}\n"

    // Responsive styles
    if (options.includeResponsive && element.responsiveStyles) {
      const breakpoints = {
        mobile: "(max-width: 767px)",
        tablet: "(min-width: 768px) and (max-width: 1023px)",
        desktop: "(min-width: 1024px)",
      }

      Object.entries(element.responsiveStyles).forEach(([breakpoint, styles]) => {
        if (styles && Object.keys(styles).length > 0) {
          css += `\n@media ${breakpoints[breakpoint as Breakpoint]} {\n`
          css += `  .${className} {\n`
          Object.entries(styles).forEach(([property, value]) => {
            css += `    ${camelToKebab(property)}: ${value};\n`
          })
          css += "  }\n"
          css += "}\n"
        }
      })
    }

    // Generate styles for children
    if (element.children) {
      css += generateCSS(element.children, options)
    }
  })

  return options.minifyCode ? minifyCSS(css) : css
}

export function generateHTML(
  elements: BuilderElement[],
  options: ExportOptions = { includeResponsive: true, minifyCode: false, includeComments: true },
): string {
  const css = generateCSS(elements, options)

  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated Website</title>
  <style>
${css}
  </style>
</head>
<body>
`

  if (options.includeComments) {
    html += "  <!-- Generated by Website Builder -->\n"
  }

  html += generateElementHTML(elements, 1)
  html += "</body>\n</html>"

  return options.minifyCode ? minifyHTML(html) : html
}

function generateElementHTML(elements: BuilderElement[], indent = 0): string {
  let html = ""
  const indentStr = "  ".repeat(indent)

  elements.forEach((element) => {
    const className = `element-${element.id}`
    const tag = getHTMLTag(element.type)

    html += `${indentStr}<${tag} class="${className}"`

    // Add element-specific attributes
    if (element.props) {
      Object.entries(element.props).forEach(([key, value]) => {
        if (key === "href" && value) {
          html += ` href="${value}"`
        } else if (key === "alt" && value) {
          html += ` alt="${value}"`
        } else if (key === "openInNewTab" && value) {
          html += ` target="_blank" rel="noopener noreferrer"`
        }
      })
    }

    html += ">"

    // Add content
    if (element.type === "image") {
      // Self-closing for images
      html = html.slice(0, -1) + ` src="${element.content || "/placeholder.svg"}" />\n`
    } else {
      if (element.children && element.children.length > 0) {
        html += "\n"
        html += generateElementHTML(element.children, indent + 1)
        html += `${indentStr}</${tag}>\n`
      } else {
        html += element.content || ""
        html += `</${tag}>\n`
      }
    }
  })

  return html
}

function getHTMLTag(elementType: string): string {
  const tagMap: Record<string, string> = {
    heading: "h1",
    paragraph: "p",
    image: "img",
    button: "button",
    section: "section",
    grid: "div",
    navigation: "nav",
    footer: "footer",
    form: "form",
  }

  return tagMap[elementType] || "div"
}

function camelToKebab(str: string): string {
  return str.replace(/([a-z0-9]|(?=[A-Z]))([A-Z])/g, "$1-$2").toLowerCase()
}

function minifyCSS(css: string): string {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, "") // Remove comments
    .replace(/\s+/g, " ") // Replace multiple spaces with single space
    .replace(/;\s*}/g, "}") // Remove semicolon before closing brace
    .replace(/\s*{\s*/g, "{") // Remove spaces around opening brace
    .replace(/;\s*/g, ";") // Remove spaces after semicolon
    .trim()
}

function minifyHTML(html: string): string {
  return html
    .replace(/<!--[\s\S]*?-->/g, "") // Remove comments
    .replace(/\s+/g, " ") // Replace multiple spaces with single space
    .replace(/>\s+</g, "><") // Remove spaces between tags
    .trim()
}

export function downloadFile(content: string, filename: string, contentType = "text/plain") {
  const blob = new Blob([content], { type: contentType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// Multi-page export utilities
export function generateMultiPageHTML(
  pages: BuilderPage[],
  options: ExportOptions = { includeResponsive: true, minifyCode: false, includeComments: true, generateRouting: true },
): { html: Map<string, string>; css: string; index: string } {
  const allCSS = new Set<string>()
  const htmlPages = new Map<string, string>()

  // Generate CSS for all pages (combined)
  pages.forEach(page => {
    const pageCSS = generateCSS(page.elements, options)
    allCSS.add(pageCSS)
  })

  const combinedCSS = Array.from(allCSS).join('\n\n')

  // Generate HTML for each page
  pages.forEach((page, index) => {
    const pageName = page.metadata?.route || page.name.toLowerCase().replace(/\s+/g, '-')
    const fileName = index === 0 ? 'index' : pageName
    
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${page.metadata?.title || page.name}</title>
  ${page.metadata?.description ? `<meta name="description" content="${page.metadata.description}">` : ''}
  ${page.metadata?.favicon ? `<link rel="icon" href="${page.metadata.favicon}">` : ''}
  <link rel="stylesheet" href="styles.css">
  ${options.generateRouting ? '<script src="router.js"></script>' : ''}
</head>
<body>
${options.includeComments ? `  <!-- Page: ${page.name} -->\n` : ''}
${generateElementHTML(page.elements, 1)}
${options.generateRouting ? generateNavigationMenu(pages) : ''}
</body>
</html>`

    htmlPages.set(fileName, options.minifyCode ? minifyHTML(html) : html)
  })

  // Generate index page if not exists
  if (!htmlPages.has('index') && pages.length > 0) {
    const firstPage = pages[0]
    const indexHTML = htmlPages.values().next().value
    htmlPages.set('index', indexHTML)
  }

  // Generate simple client-side router
  const routerJS = options.generateRouting ? generateRouter(pages) : ''

  return {
    html: htmlPages,
    css: combinedCSS,
    index: routerJS,
  }
}

function generateNavigationMenu(pages: BuilderPage[]): string {
  return `
  <!-- Navigation Menu -->
  <nav style="padding: 1rem; background: #f5f5f5; border-top: 1px solid #ddd; position: fixed; bottom: 0; width: 100%;">
    <ul style="list-style: none; display: flex; gap: 1rem; margin: 0; padding: 0; justify-content: center;">
${pages.map((page, index) => {
  const pageName = page.metadata?.route || page.name.toLowerCase().replace(/\s+/g, '-')
  const href = index === 0 ? 'index.html' : `${pageName}.html`
  return `      <li><a href="${href}" style="text-decoration: none; color: #333; font-weight: 500;">${page.name}</a></li>`
}).join('\n')}
    </ul>
  </nav>`
}

function generateRouter(pages: BuilderPage[]): string {
  return `// Simple client-side router for multi-page navigation
const routes = ${JSON.stringify(
    pages.map((page, index) => ({
      name: page.name,
      path: page.metadata?.route || (index === 0 ? '/' : `/${page.name.toLowerCase().replace(/\s+/g, '-')}`),
      file: index === 0 ? 'index.html' : `${page.metadata?.route || page.name.toLowerCase().replace(/\s+/g, '-')}.html`,
    }))
  )};

// Handle navigation
document.addEventListener('DOMContentLoaded', () => {
  const currentPath = window.location.pathname;
  
  // Add active class to current page link
  const links = document.querySelectorAll('nav a');
  links.forEach(link => {
    if (link.getAttribute('href') === currentPath.split('/').pop()) {
      link.style.color = '#0066cc';
      link.style.fontWeight = 'bold';
    }
  });
});`
}

export function downloadMultiPageProject(
  pages: BuilderPage[],
  projectName: string,
  options: ExportOptions = { includeResponsive: true, minifyCode: false, includeComments: true, generateRouting: true },
) {
  const { html, css, index } = generateMultiPageHTML(pages, options)

  // Create a simple file structure explanation
  const readme = `# ${projectName}

Multi-page website generated by Website Builder.

## File Structure

- \`index.html\` - Home page${pages.length > 1 ? `\n${pages.slice(1).map(p => `- \`${p.metadata?.route || p.name.toLowerCase().replace(/\s+/g, '-')}.html\` - ${p.name}`).join('\n')}` : ''}
- \`styles.css\` - Combined styles for all pages
${options.generateRouting ? '- `router.js` - Client-side routing\n' : ''}
## Pages

${pages.map((p, i) => `${i + 1}. **${p.name}** (${p.elements.length} elements)${p.metadata?.description ? `\n   - ${p.metadata.description}` : ''}`).join('\n')}

## How to Use

1. Extract all files to a folder
2. Open \`index.html\` in your web browser
3. Navigate between pages using the menu

---
Generated on ${new Date().toLocaleDateString()}
`

  // For now, download files individually (in a real app, you'd create a ZIP)

  // Download CSS
  downloadFile(css, 'styles.css', 'text/css')

  // Download each HTML page
  setTimeout(() => {
    html.forEach((content, filename) => {
      downloadFile(content, `${filename}.html`, 'text/html')
    })
  }, 500)

  // Download router if enabled
  if (options.generateRouting) {
    setTimeout(() => {
      downloadFile(index, 'router.js', 'text/javascript')
    }, 1000)
  }

  // Download README
  setTimeout(() => {
    downloadFile(readme, 'README.md', 'text/markdown')
  }, 1500)

  return { success: true, fileCount: html.size + 2 + (options.generateRouting ? 1 : 0) }
}
