import type { BuilderElement, Breakpoint } from "./builder-types"

export interface ExportOptions {
  includeResponsive: boolean
  minifyCode: boolean
  includeComments: boolean
}

export function generateCSS(
  elements: BuilderElement[],
  options: ExportOptions = { includeResponsive: true, minifyCode: false, includeComments: true },
): string {
  let css = ""

  if (options.includeComments) {
    css += "/* Generated by Website Builder */\n"
    css += "/* Base styles */\n"
  }

  // Base CSS reset and utilities
  css += `
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  line-height: 1.6;
  color: #333;
}

img {
  max-width: 100%;
  height: auto;
}

button {
  cursor: pointer;
  border: none;
  outline: none;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 1rem;
}
`

  // Generate styles for each element
  elements.forEach((element, index) => {
    const className = `element-${element.id}`

    if (options.includeComments) {
      css += `\n/* ${element.type} - ${element.id} */\n`
    }

    css += `.${className} {\n`

    // Base styles
    Object.entries(element.styles || {}).forEach(([property, value]) => {
      css += `  ${camelToKebab(property)}: ${value};\n`
    })

    css += "}\n"

    // Responsive styles
    if (options.includeResponsive && element.responsiveStyles) {
      const breakpoints = {
        mobile: "(max-width: 767px)",
        tablet: "(min-width: 768px) and (max-width: 1023px)",
        desktop: "(min-width: 1024px)",
      }

      Object.entries(element.responsiveStyles).forEach(([breakpoint, styles]) => {
        if (styles && Object.keys(styles).length > 0) {
          css += `\n@media ${breakpoints[breakpoint as Breakpoint]} {\n`
          css += `  .${className} {\n`
          Object.entries(styles).forEach(([property, value]) => {
            css += `    ${camelToKebab(property)}: ${value};\n`
          })
          css += "  }\n"
          css += "}\n"
        }
      })
    }

    // Generate styles for children
    if (element.children) {
      css += generateCSS(element.children, options)
    }
  })

  return options.minifyCode ? minifyCSS(css) : css
}

export function generateHTML(
  elements: BuilderElement[],
  options: ExportOptions = { includeResponsive: true, minifyCode: false, includeComments: true },
): string {
  const css = generateCSS(elements, options)

  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated Website</title>
  <style>
${css}
  </style>
</head>
<body>
`

  if (options.includeComments) {
    html += "  <!-- Generated by Website Builder -->\n"
  }

  html += generateElementHTML(elements, 1)
  html += "</body>\n</html>"

  return options.minifyCode ? minifyHTML(html) : html
}

function generateElementHTML(elements: BuilderElement[], indent = 0): string {
  let html = ""
  const indentStr = "  ".repeat(indent)

  elements.forEach((element) => {
    const className = `element-${element.id}`
    const tag = getHTMLTag(element.type)

    html += `${indentStr}<${tag} class="${className}"`

    // Add element-specific attributes
    if (element.props) {
      Object.entries(element.props).forEach(([key, value]) => {
        if (key === "href" && value) {
          html += ` href="${value}"`
        } else if (key === "alt" && value) {
          html += ` alt="${value}"`
        } else if (key === "openInNewTab" && value) {
          html += ` target="_blank" rel="noopener noreferrer"`
        }
      })
    }

    html += ">"

    // Add content
    if (element.type === "image") {
      // Self-closing for images
      html = html.slice(0, -1) + ` src="${element.content || "/placeholder.svg"}" />\n`
    } else {
      if (element.children && element.children.length > 0) {
        html += "\n"
        html += generateElementHTML(element.children, indent + 1)
        html += `${indentStr}</${tag}>\n`
      } else {
        html += element.content || ""
        html += `</${tag}>\n`
      }
    }
  })

  return html
}

function getHTMLTag(elementType: string): string {
  const tagMap: Record<string, string> = {
    heading: "h1",
    paragraph: "p",
    image: "img",
    button: "button",
    section: "section",
    grid: "div",
    navigation: "nav",
    footer: "footer",
    form: "form",
  }

  return tagMap[elementType] || "div"
}

function camelToKebab(str: string): string {
  return str.replace(/([a-z0-9]|(?=[A-Z]))([A-Z])/g, "$1-$2").toLowerCase()
}

function minifyCSS(css: string): string {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, "") // Remove comments
    .replace(/\s+/g, " ") // Replace multiple spaces with single space
    .replace(/;\s*}/g, "}") // Remove semicolon before closing brace
    .replace(/\s*{\s*/g, "{") // Remove spaces around opening brace
    .replace(/;\s*/g, ";") // Remove spaces after semicolon
    .trim()
}

function minifyHTML(html: string): string {
  return html
    .replace(/<!--[\s\S]*?-->/g, "") // Remove comments
    .replace(/\s+/g, " ") // Replace multiple spaces with single space
    .replace(/>\s+</g, "><") // Remove spaces between tags
    .trim()
}

export function downloadFile(content: string, filename: string, contentType = "text/plain") {
  const blob = new Blob([content], { type: contentType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
